[pytest]
# Explicitly registers the root project directory into the Python runtime search path
pythonpath = .

# Specifies the directory paths where pytest should scan for test script cases
testpaths = tests

# Configures the pytest-asyncio plugin to automatically handle async path definitions
asyncio_mode = auto
